### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Rourke101** [eneam/mboxviewer#1]
I am trying to read a 15GB mbox file. After the initial load it says "Out of memory". (Note - My computer has more than 20GB of free memory)

**Comment by zigm** [comment]
Hmm, that should work. The largest mbox archive file I tested was 9GB. Let me know which version you are running.  Please remove .mboxview file corresponding to your archive file and try again. Is your mail file from Google or some other provider? When the mbox viewer starts parsing your mbox file,  you should see the progress bar. Do you see out of memory immediately ? I did see out of memory in the past but it was due to the version mismatch of .mboxview file but I don't think this is what is happening in your case. Remove .mboxview file and let me know if that helps. And provide as many details as you can.

**Comment by zigm** [comment]
Did not mean to close the issue, please reply to my follow up comment.

**Comment by zigm** [comment]
See my reply I posted on github.

**Comment by zigm** [comment]
When you select one of the installed archive files for the first time, the mbox viewer will parse the archive and create MailArchiveFileName.mboxview index file. The size of the mboxview file should be much smaller than the corresponding mail file. Mbox viewer loads the index file into the memory to boost performance.

**Comment by zigm** [comment]
Created 18GB mail file by concatenating twice the same 9GB mbox mail file and parsed using mbox viewer v 1.0.3.0. Didn't see out of memory failure. Waiting for more details from you.,

**Comment by zigm** [comment]
Thank you for taking time to raise the issue. Would like to resolve the
reported issue but will need your help to provide a bit more details.

**Comment by zigm** [comment]
Wondering if you did clone the master branch, build the mboxview and run. This may not always work since the master branch might be in unknown state. The projects doesn't have feature branches so you need to always checkout to the released tag and rebuild.  May not be the best practice but I am the only active developer at the moment.

**Comment by zigm** [comment]
Resolved Out of Memory crash in v1.0.3.1. The second user reported the same issue. Worked with that user to resolve the issue. Appreciate if you could verify the fix running your large mail archive.

Complete list of enhancements is listed below.
v 1.0.3.1
 - To improve mboxview, please post reviews on what works, what doesn't, create bug tickets and enhancment requests;
 - RESOLVED Out of Memory crash due to corrupted mboxview index file created during initial parsing of mail archive;
 - Added capability to merge/concatenate multiple archive files and remove duplicate mails;
 - Added option to print directly to PDF without user interaction by leveraging external HTML to PDF converter tools such as Chrome Browser or wkhtmltopdf;
 - Added option to print each mail to a separate PDF file;
 - Added scripts to merge per mail PDF files to support printing large number of mails to a single PDF file;
 - Added vertical bar in the first column to mark mails that are also on the User Selected Mails list;
 - Added handling of CTRL-A to select all mails in the Summary Window. Windows must be selected first;
 - Added option to insert Page Break after each mail when printing multiple mails to single Text or PDF file;
 - Added option to remove/add the background color to the mail header;
 - Added options to export CC and BCC header fields to CSV spreadsheet file;
 - Added CC and BCC fields to a search criteria in Find Advanced and Find dialog;
 - Added option to limit the maximum text length when printing mail text to CSV;
 - Updated Help options;
 - Updated User Manual to describe new and updated features;

**Comment by Rourke101** [comment]
Sorry, I didn't get notified of this :-0 

Latest version opens well a 14GB file. Well done

**Comment by zigm** [comment]
Thanks for taking time to verify the fix and provide feedback.  I helps to
stay motivated -:) and makes tool better.
