### ISSUE TITLE
Mbox attachment file of chinese file name encoding errors

### ISSUE THREAD

**Issue by owllyi** [eneam/mboxviewer#4]
![image](https://user-images.githubusercontent.com/5955179/74004124-d59a8700-49af-11ea-8875-280c261b8074.png)

Please help~

**Comment by owllyi** [comment]
![image](https://user-images.githubusercontent.com/5955179/74004493-de3f8d00-49b0-11ea-8d3a-660c44104cfe.png)

This is the correct file name.

**Comment by zigm** [comment]
Hi,

Thank you for raising the issue. The mbox viewer should be able to handle
mail text and mai lheaders in chinese but  there are limitation as far as
handling attachment names encoded with the character sets other than ansi.

If you can  provide more information I can investigate if the mbox viewer
can be enhanced to provide better support for the chinese file name.

What I would need is the raw email that demonstrates the issue. Please make
sure that the mail doesn't contain sensite information before making
available to me.

You can export single mail by setting File->Options>Export EML to yes and
than left double click on the email.

This should open the folder with the message.eml file inside. Attach the
file to the ticket.

Regards,
Zbigniew

**Comment by owllyi** [comment]
I've uploaded an attachment. My test mbox file. Thanks a lot.
[testmbox.zip](https://github.com/eneam/mboxviewer/files/4169570/testmbox.zip)

**Comment by zigm** [comment]
I examined the provided mbox file (thanks) and this is known issue due to
mbox viewer not compiled with UNICODE support.

So it is not decode/encode issue per se since the same file name will be
presented correctly if placed as the mail subject.

Currently the attachment names are mapped to alpha numeric ansi and that is
why you see many underscores. The file  content should be valid.

Header fields is the only place at the moment that the text wil be
presented correctly.

Generic support for inline and non inline attachment names  is a bit more
challenging to support in non UNICODE application.

I was delaying the support until I  port the mbox viewer to UNICODE.

However, I wil take another look if there is a low/medium risk solution to
the issue you raised. Let you know what I figured out.

Cheers,
Zbigniew

**Comment by owllyi** [comment]
Support for Unicode is a big change.
Looking forward to any workaround to fix the issue.

**Comment by zigm** [comment]
Want to provided an update. I did manage to enhance the attachment window to properly display attachment names encoded in UTF8, etc. Had to implement Custom Draw as I did to display correctly text in the mail summary window.  

Looking further I would need to convert many places to explicity use so called wide characters and wide characters function calls. I did prototype changes in few places. There are many places to touch.

Since I was in the middle of working on some other enhancements I suspended investigation into proper support of any character sets in non UNICODE mbox viewer and completed work on the new release v1.0.3.7.

I will keep looking into feasibility to resolve the issue you raised but solution or conclusion will take some time.  Let you know of any progress I make.

**Comment by zigm** [comment]
I created new version 1.0.3.8 of the viewer on Github ad Sourceforge to address the issue you raised.
I hope you find time to evaluate the enhancement and provide feedback.
There is still no full support for Unicode but rather the targeted enhancements to address attachment names. The solution supports Unicode names of non-inline attachments, i.e. attachments not embedded into email text/message. I also had to enhance the export to CSV feature to include attachment names in Unicode. I also had to enhance the internal picture viewer, domino effect -:)
Hope v1.0.3.8 resolves issue you raised but if there are cases it doesn't address I would appreciate if you can export individual emails to the eml files and provide to me for examination (assuming emails don't contain sensitive information).
Thanks for your time and effort.

**Comment by zigm** [comment]
Hi ,

Let me know if you will  be able to verify the fix I posted lately on
Github and Sourceforge.

Cheers,
Zbigniew

**Comment by owllyi** [comment]
ok, I'll have a try tonight.

**Comment by zigm** [comment]
Thanks, that helps.

**Comment by owllyi** [comment]
![image](https://user-images.githubusercontent.com/5955179/77068120-07782200-6a21-11ea-95b5-385dd1982cba.png)
The Chinese attachment file name is correct now. I will check my Gmail mbox file later.
Thank you very much.

**Comment by zigm** [comment]
Thanks for taking time to verify the fix and provide feedback. It helps to
stay motivated and makes tool better.
Please feel free to offer suggestions and/or request new features.
