### ISSUE TITLE
Can't see message body in message window

### ISSUE THREAD

**Issue by Nagy53Janos** [eneam/mboxviewer#40]
Hi! I'm complitly new to mboxviewer, but I can't se the message body in the message window. I see the message header, attached files but not the message text. When I doublclick on a message in the summary window the program opens then File Explorer and there I see a html-file. This file is containing the message body, but it is not shown in mboxviewer. What is wrong?
Best Regards
Janos Nagy

**Comment by zigm** [comment]
Hi Janos,

For a moment I thought that maybe the message/text  window was somehow minimized to zero and needs to be resized manually from the bottom line. However, since you can see attachments, it doesn't appear to be the case.

When you double left click on the mail in the summary window, the mbox viewer will open the folder with eml, html and attachment files as you noticed.

Not sure why the mail text is not shown. I would need sample mail file from the folder created by double left click.  This folder should contain the *.eml file that contain single mail file.  You need to set "File->Options->Export EML->yes" option. 

Hope you find some email without confidential text. You may need to append .txt extension to the eml file in order to attach to this ticket.

Also, please try to open one of the email in the Browser. Right click on email in the summary and select "Open in Browser".

Also, let me know what version of Windows you are running and the source of email files such as Gmail, etc.

**Comment by Nagy53Janos** [comment]
Hi zigm,
and thank you for very quick response. Let me say first of all that I really appreciate mbox viewer. The program would be perfect for my purposes if it only displayed the message body too. I am attaching a document that shows what it looks like for me along with a zip file that contains the directory you requested.
Thanks for your help!
Best regards
Janos

[Simple mbox viewer.pdf](https://github.com/eneam/mboxviewer/files/10280257/Simple.mbox.viewer.pdf)
[mboxview.zip](https://github.com/eneam/mboxviewer/files/10280260/mboxview.zip)

**Comment by zigm** [comment]
Hi Janos,

I don't see any issues opening the provided eml file on Window 10 Pro and Windows 11 Home. See attached.

Potential issue is that you are missing the legacy MSHTML (Trident) engine which is the underlying platform for Internet Explorer 11.  It is located in C:\Windows\System32\mshtml.dll'.  MBox Viewer relies on MSHTML.  In the future WebView2 engine will be used once it is stable.

You may want to also check Event Viewer for any complains.  Let me know what you found out.

![image](https://user-images.githubusercontent.com/36137255/209021402-2f0a1ffd-711b-4ad8-9c16-0a6dc605bb29.png)

**Comment by zigm** [comment]
You can also try to run the mboxview.exe  from  mbox-viewer.exe-v1.0.3.36\ReleasePlusStackTrace folder. Not sure it will provide any additional insides but it is worth to try.

**Comment by zigm** [comment]
I was curious and attempted to rename the mshtml.dll file to observe MBox Viewer behavior when the mshtml.dll is missing. However, Windows system prevented me from renaming the file.  Anyway, the mshtml.dll is used by the Edge Browser in the legacy mode and therefore it is very unlikely it is missing on your system.

Checking the Event Viewer, short of building and running Mbox Viewer under the debugger,  may provide some insides.

Running the debug version of MBox Viewer is likely to help to identify the issue but I would need to provide you the debug version of MBox Viewer if you are interested.

**Comment by zigm** [comment]
No new developments on this issue, not able to resolve,  closing.
