### ISSUE TITLE
Feature request - print/export all attachments

### ISSUE THREAD

**Issue by mbcbus** [eneam/mboxviewer#6]
If would be great if two updates were made:
1) The ability to export a delimited list of attached files on an email
2) The ability to export all attachments from the mbox to a designated folder location.

**Comment by zigm** [comment]
Hi,

*1. The ability to export a delimited list of attached files on an email *

The mbox viewer has an option to export selected mail header fields and
attachment file names to CSV spreadsheet. Currently you would have to
select/highlight  at least two mails for export.
Would this option work for you ?


*2. The ability to export all attachments from the mbox to a designated
folder location. *

It is very likely, attachments from different mails have the same name.

Would you need to know which mail contributed an attachment?

I don't think separate folder per mail is acceptable. Not sure what would
be a good solution.

Cheers,
Zbigniew

**Comment by zigm** [comment]
*2. The ability to export all attachments from the mbox to a designated
folder location. *

How about enhancing export to CVS dialog to support ability to specify destination folder and whether to generate all attachments?

I would prepend mail index from the CSV file to each attachment name, ie.

Form.doc -> 3_Form.doc.

**Comment by zigm** [comment]
Hi,

Created new release v1.0.3.14 that provides option to export all attachments. To avoid attachment name clashes, unique prefix is prepended to each attachment name.

Hope you find time to test the feature and provide feedback.

Zbigniew

**Comment by rettops** [comment]
Thank you for adding "Export All Attachments" - very useful!

I have an mbox message that has attachments, but they are each given a 'Content-Disposition: inline' rather than 'Content-Disposition:attachment', so they don't export to the attachment cache.  They have no reference in the html, so they don't export to the image cache either.  Is there some setting that I'm missing that would result in them getting exported?

**Comment by zigm** [comment]
I am aware of this potential issue. I possibly didn't make the best choice. There is inconsistency how potential attachments are handled currently. I believe you would have access to such attachments when you open a single email and File->Attachment Config->Show All Attachments is set.  

Probably could export all attachments marked as attachments and "attachments" that don't have reference in the raw mail. That would results in many attachments that are not attachments since there are mails that seem to do whatever they want. However. more might better in this case and allow users to  decide whether attachment is valid or not. 

I could possibly rely on the configuration in the Attachment Config or add a separate configuration for exporting to Eml.

Anyway, the short answer is that currently there is no work around for Export All Mails as Eml option. What would be your prefer solution?

**Comment by zigm** [comment]
I hesitated in the past but possibly new dialog could be added that would allow users to configure how and what to export:

1. What to export
        - attachments marked as attachments but not referenced in the mail content, plus
        - attachments referenced in the mail content, plus
        - inline attachments  not referenced in the mail content, plus
        - inline attachments referenced in the mail content

2. How to export
       - create separate folder per mail with attachments. Name of the folder would leverage the name template for printing
       - create prefix for attachment as it is today, possibly extending with From field

**Comment by rettops** [comment]
I think it would probably be enough just to honor the setting for "Show All Attachments" when doing an "Export All Attachments", the same as is done when viewing the attachments in/on a single email.  I was a little surprised when they acted differently.

**Comment by zigm** [comment]
Thanks. I agree that the export of attachments should be consistent. I will review the current processing and provide an update. Note that both attachments labeled as the attachments and inline attachments may or may not be referenced in the message which raises interesting questions.

**Comment by zigm** [comment]
Released v1.0.3.18 of the mbox viewer to hopefully resolve the reported issue with inline attachments.
Hope you find time to verify the solution and provide feedback.

The File->Attachment Config control whether images embedded into message will also be exported.

**Comment by rettops** [comment]
It worked great for me, thanks!

**Comment by zigm** [comment]
Thanks for feedback.  Good to know that it worked and I can close the issue.
