### ISSUE TITLE
Be more flexible with the initial line of a message (From ...)

### ISSUE THREAD

**Issue by mherrmann3** [eneam/mboxviewer#9]
*mboxviewer* fails opening mbox files, whose `From` line (i.e. the first line of a message) is either not specified:

    From 

or where the origin is not specified:

    From - Tue Apr 28 16:18:00 2020

(these are both used by Thunderbird internally). Similarly, mbox files created with the [imapbackup](https://github.com/rcarmo/imapbackup) script can also not be read; their `From` lines look like this:

    From nobody Tue Apr 28 16:18:00 2020

Other tools, such as [fetchmail](https://www.fetchmail.info/fetchmail-man.html) or [IMAPsize](https://www.broobles.com/imapsize) insert the original sender's email address (with the @), so that *mboxviewer* has no problems reading those.

Can you make reading mbox files more flexible by accounting for these possible `From` formats? (Its content doesn't matter anyways).

Thank you very much!

**Comment by zigm** [comment]
Hello,

Thanks for raising the issue and providing examples. I will investigate and
provide an update and/or make new release.

Zbigniew

**Comment by zigm** [comment]
Hi,

I reviewed the current parsing of mbox files and apparently, in the last few releases,  I added stronger check to validate the From starting line of an email .  There are many variants of  mbox file format and thus that creates challenges to implement the reliable parser. I added stronger check of the "From "  lines to avoid false positive when the From line is present in the mail text.

Currently the "From " line to be valid must also contain two ':' colon characters, six digits and one '@' character or "at" string. 

Therefore as you indicated the mbox viewer is not able to handle some of the mbox files with different format of the From line.

I will relax the rule and create new release. Not sure yet about the solution. Would like to have strongest check possible to validate From line to avoid false positive. If I make the check as a configurable option it may not be the most user friendly solution. May to need to preprocess few mails first  to figure out the format of the From line. Not sure if the From line format may differ across multiple mails withing the same mbox file, thus creating additional challenge.

Not sure about considering just From without additional context as the valid mail beginning, it will likely result in false positive.

Will investigate and provide an update. If you have additional comments or suggestions, please don't hesitate to offer.

Zbigniew

**Comment by mherrmann3** [comment]
Good point & thanks for your detailed reply! When I was looking at the mbox file contents, I was surprised that there is no clear message separator. Maybe you can make it dependent on the content of the following lines? That is, it appears that the ominous `From` line is always followed by a line starting with `Received:`, unless the mbox file was generated with `fetchmail`, in which case it's followed by a line `MIME-Version: 1.0`, and then by `Received:`.

Another idea is to look at how the [ImportExportTools NG](https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/) Thunderbird addon implements this, who's main task is also to read mbox files. I had a quick look at it, but didn't find a clear solution to our problem. If you want to have a look: I guess to most interesting source files are [mboximport.js](https://github.com/thundernest/import-export-tools-ng/blob/master/src/chrome/content/mboximport/mboximport.js) and [utils.js](https://github.com/thundernest/import-export-tools-ng/blob/master/src/chrome/content/mboximport/utils.js).

**Comment by zigm** [comment]
Hi,

Yesterday I was browsing Web again and rereading many posts about From line
mail separator. It appears that there are more than 20 different formats of
From line separator so it is risky to rely on one specific format as I did.
Most common , sort of a standard, is as follow

From sender-address date-and time

Date and time are pretty much always in the standard format. The
sender-address is however not as you pointed out and it can be '-' or
"nobody" or "john at gmail" or "john@mail" or some other formats. So best
is to ignore the sender-address when validating the From line.
Theoretically , whatever follows after the "From " can be ignored assuming
that one or more '>' character are inserted in front of From in the mail
text assuming the mbox protocol is observed.

Initial implementation was ignoring whatever follows after the "From "
text. However, one of the users reported the issue (due to lack of '>' in
from of the From) and I added stronger check to validate the From mail
separator.
The change is clearly too restrictive and needs to be updated. I could
disable extra check for now and investigate better or appropriate
solution.  The cases with invalid From in the text are rare. You would be
surprised how many exceptions any mbox viewer needs to implement to support
poorly formatted mbox mails.

I will also review the links you provided and decide how to progress the
issue.

Best Regards,
Zbigniew

**Comment by mherrmann3** [comment]
Thanks for your efforts in reviewing the isssue! It's quite shocking, cruel, & sad that the mail separator is not standardized.

I hope you find a solution that satisfies all your users. For me, you don't need to release a new version with just the restrictive `From`-checks disabled. Instead, can you point me to the *mboxviewer* version before you implemented those? Thanks & happy coding!

**Comment by zigm** [comment]
I released the v1.0.3.10 of the mbox viewer on Github and Sourceforge to
hopefully resolve the issue you raised. Let me know if it works now for you.
Created new release to avoid searching the older releases and evaluating
potential issues within each of them.

**Comment by mherrmann3** [comment]
Great! I have tested the new release and I could open (read: view without issues) every mbox file that I have. Thanks a lot for your effort! I hope this doesn't render your tool incompatible with other users' mbox formats...

Btw: I was wrong with my previous statement that a `From` line is always followed by a `Received:` line (or `MIME-Version:`). I found more possible candidates of subsequent (i.e. initial) properties: `Date:`, `Delivered-To:`, `Return-Path:`, `X-Mozilla-Status:`, `Message-ID:`, `FCC:`. So I guess this is not a clear additional discriminator. 🤕

**Comment by zigm** [comment]
Glad it works now.  Anyway, looking ahead of From_ is a good idea to decide
whether From_ is valid mail separator. It means a bit more complexity and
possibly some cpu overhead. Will investigate.
I am working now on some user requested enhancements and may also make
additional enhancements to processing of From_.

**Comment by zigm** [comment]
Closing the ticket.
